import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const FACULTY_DATA = [
  { id: 1, title: 'Prof.', name: 'Umesh Nanaware', fullName: 'Prof. Umesh Nanaware', block: 'S-001', floor: '2nd', cabinPosition: 'Cabin 1', cabinType: 'numbered', rawRemark: 'Sharing cabin with Prof. Chhaya Mhaske', remarkType: 'sharing', isHOD: false },
  { id: 3, title: 'Prof.', name: 'Raju Gurav', fullName: 'Prof. Raju Gurav', block: 'S-001', floor: '2nd', cabinPosition: 'Cabin 3', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 4, title: 'Prof.', name: 'Mayuresh Gulame', fullName: 'Prof. Mayuresh Gulame', block: 'S-001', floor: '2nd', cabinPosition: 'Cabin 4', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 5, title: 'Dr.', name: 'Reena Gunjan', fullName: 'Dr. Reena Gunjan', block: 'N-003', floor: '2nd', cabinPosition: 'N003', cabinType: 'numbered', rawRemark: 'Old Seating Arrangement', remarkType: 'note', isHOD: false },
  { id: 6, title: 'Dr.', name: 'Nandkishor Karlekar', fullName: 'Dr. Nandkishor Karlekar', block: 'S-211', floor: '2nd', cabinPosition: 'A (Right First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 7, title: 'Prof.', name: 'Nilesh Thorat', fullName: 'Prof. Nilesh Thorat', block: 'S-211', floor: '2nd', cabinPosition: 'B (Right Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 8, title: 'Prof.', name: 'Pratiksha Malvathkar', fullName: 'Prof. Pratiksha Malvathkar', block: 'S-211', floor: '2nd', cabinPosition: 'C (Right Third)', cabinType: 'lettered', rawRemark: 'Due Medical Issue — Shifted from 9th Floor to 2nd', remarkType: 'medical_leave', isHOD: false },
  { id: 9, title: 'Prof.', name: 'Arati Pimpalkar', fullName: 'Prof. Arati Pimpalkar', block: 'S-211', floor: '2nd', cabinPosition: 'D (Right Fourth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 10, title: 'Prof.', name: 'Komal Munde', fullName: 'Prof. Komal Munde', block: 'S-211', floor: '2nd', cabinPosition: 'E (Left Fourth)', cabinType: 'lettered', rawRemark: 'Leg Injury Issue', remarkType: 'medical_leave', isHOD: false },
  { id: 11, title: 'Prof.', name: 'Priya Khune', fullName: 'Prof. Priya Khune', block: 'S-211', floor: '2nd', cabinPosition: 'F (Left Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 13, title: 'Prof.', name: 'Avinash Utikar', fullName: 'Prof. Avinash Utikar', block: 'S-211', floor: '2nd', cabinPosition: 'H (Left First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 14, title: 'Prof.', name: 'Sushma Mehetre', fullName: 'Prof. Sushma Mehetre', block: 'S-211', floor: '2nd', cabinPosition: 'A (Right First) — Wing 2', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 15, title: 'Dr.', name: 'Sangita Patil', fullName: 'Dr. Sangita Patil', block: 'S-211', floor: '2nd', cabinPosition: 'B (Right Second) — Wing 2', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 16, title: 'Dr.', name: 'Chandrashekhar Karamgaonkar', fullName: 'Dr. Chandrashekhar Karamgaonkar', block: 'S-211', floor: '2nd', cabinPosition: 'C (Right Third) — Wing 2', cabinType: 'lettered', rawRemark: 'Prof. Supriya Mandhare Left', remarkType: 'note', isHOD: false },
  { id: 17, title: 'Dr.', name: 'Aman Sing', fullName: 'Dr. Aman Sing', block: 'S-309', floor: '3rd', cabinPosition: 'D — Corner', cabinType: 'lettered', rawRemark: 'Shifted from 9th Floor to 3rd as per email', remarkType: 'shifted', isHOD: false },
  { id: 18, title: 'Prof.', name: 'Savitri Chougule', fullName: 'Prof. Savitri Chougule', block: 'S-309', floor: '3rd', cabinPosition: 'E — Front', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 19, title: 'Prof.', name: 'Bhausaheb Salave', fullName: 'Prof. Bhausaheb Salave', block: 'S-309', floor: '3rd', cabinPosition: 'F — Front', cabinType: 'lettered', rawRemark: 'Shifted from 9th Floor to 3rd as per email', remarkType: 'shifted', isHOD: false },
  { id: 20, title: 'Prof.', name: 'Babeetta Bhagat', fullName: 'Prof. Babeetta Bhagat', block: 'S-309', floor: '3rd', cabinPosition: 'G — Front', cabinType: 'lettered', rawRemark: 'Due Medical Issue — Shifted from 9th Floor', remarkType: 'medical_leave', isHOD: false },
  { id: 21, title: 'Dr.', name: 'Sunita Parinam', fullName: 'Dr. Sunita Parinam', block: 'S-309', floor: '3rd', cabinPosition: 'H — Front', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 22, title: 'Dr.', name: 'Aaditya Pai H', fullName: 'Dr. Aaditya Pai H', block: 'S-309', floor: '3rd', cabinPosition: 'I — Corner', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 23, title: 'Dr.', name: 'Ram Kumar', fullName: 'Dr. Ram Kumar', block: 'S-309', floor: '3rd', cabinPosition: 'J — Side', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 24, title: 'Prof.', name: 'Jyoti Ghavane', fullName: 'Prof. Jyoti Ghavane', block: 'S-309', floor: '3rd', cabinPosition: 'K — Side', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 25, title: 'Dr.', name: 'Atul Thakare', fullName: 'Dr. Atul Thakare', block: 'S-309', floor: '3rd', cabinPosition: 'L — Corner', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 26, title: 'Prof.', name: 'Shubhra Mathur', fullName: 'Prof. Shubhra Mathur', block: 'S-309', floor: '3rd', cabinPosition: 'M (Left Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 27, title: 'Dr.', name: 'Ranjana Kale', fullName: 'Dr. Ranjana Kale', block: 'S-309', floor: '3rd', cabinPosition: 'N (Left Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 28, title: 'Prof.', name: 'Disha Gabane', fullName: 'Prof. Disha Gabane', block: 'S-309', floor: '3rd', cabinPosition: 'O (Left First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 29, title: 'Prof.', name: 'Trupti Kudale', fullName: 'Prof. Trupti Kudale', block: 'S-402', floor: '4th', cabinPosition: '1', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 30, title: 'Prof.', name: 'Manisha Shitole', fullName: 'Prof. Manisha Shitole', block: 'S-402', floor: '4th', cabinPosition: '2', cabinType: 'numbered', rawRemark: 'Sharing cabin with Prof. Priyanka Gaikwad', remarkType: 'sharing', isHOD: false },
  { id: 31, title: 'Dr.', name: 'Rajani Sangappa Sajjan', fullName: 'Dr. Rajani Sangappa Sajjan', block: 'S-402', floor: '4th', cabinPosition: '3', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 32, title: 'Prof.', name: 'Pooja Oza', fullName: 'Prof. Pooja Oza', block: 'S-402', floor: '4th', cabinPosition: '4', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 33, title: 'Prof.', name: 'Deepa Mishra', fullName: 'Prof. Deepa Mishra', block: 'S-402', floor: '4th', cabinPosition: '5', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 34, title: 'Prof.', name: 'Neha Vinod Chaube', fullName: 'Prof. Neha Vinod Chaube', block: 'S-402', floor: '4th', cabinPosition: '6', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 35, title: 'Prof.', name: 'Vilas Khedekar', fullName: 'Prof. Vilas Khedekar', block: 'S-402', floor: '4th', cabinPosition: 'A (Right First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 36, title: 'Dr.', name: 'Nitin S. More', fullName: 'Dr. Nitin S. More', block: 'S-402', floor: '4th', cabinPosition: 'B (Right Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 37, title: 'Prof.', name: 'Bhagyashree Shendkar', fullName: 'Prof. Bhagyashree Shendkar', block: 'S-411', floor: '4th', cabinPosition: 'C (Right Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 38, title: 'Prof.', name: 'Sachin Jagdale', fullName: 'Prof. Sachin Jagdale', block: 'S-411', floor: '4th', cabinPosition: 'D (Right Fourth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 39, title: 'Prof.', name: 'Vaibhav Sawalkar', fullName: 'Prof. Vaibhav Sawalkar', block: 'S-411', floor: '4th', cabinPosition: 'E (Left Fourth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 40, title: 'Dr.', name: 'Mandar Mokashi', fullName: 'Dr. Mandar Mokashi', block: 'S-411', floor: '4th', cabinPosition: 'F (Left Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 41, title: 'Prof.', name: 'Yuvraj Nikam', fullName: 'Prof. Yuvraj Nikam', block: 'S-411', floor: '4th', cabinPosition: 'G (Left Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 43, title: 'Prof.', name: 'Prashant M Yelmar', fullName: 'Prof. Prashant M Yelmar', block: 'S-415', floor: '4th', cabinPosition: 'A (Right First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 44, title: 'Prof.', name: 'Kiran Shinde', fullName: 'Prof. Kiran Shinde', block: 'S-415', floor: '4th', cabinPosition: 'B (Right Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 45, title: 'Dr.', name: 'Reena Pagare', fullName: 'Dr. Reena Pagare', block: 'S-415', floor: '4th', cabinPosition: 'C (Right Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 46, title: 'Dr.', name: 'Nilima Kulkarni', fullName: 'Dr. Nilima Kulkarni', block: 'S-415', floor: '4th', cabinPosition: 'D (Right Fourth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 47, title: 'Dr.', name: 'Rameez Shamalik', fullName: 'Dr. Rameez Shamalik', block: 'S-415', floor: '4th', cabinPosition: 'E (Left Fourth)', cabinType: 'lettered', rawRemark: 'Dr. Nagesh Jadhav Shifted to HOD Room', remarkType: 'note', isHOD: false },
  { id: 48, title: 'Dr.', name: 'Ashish Bhasme', fullName: 'Dr. Ashish Bhasme', block: 'S-415', floor: '4th', cabinPosition: 'F (Left Third)', cabinType: 'lettered', rawRemark: 'Prof. Gurunath Left', remarkType: 'note', isHOD: false },
  { id: 49, title: 'Prof.', name: 'Suresh Kapare', fullName: 'Prof. Suresh Kapare', block: 'S-415', floor: '4th', cabinPosition: 'G (Left Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 50, title: 'Prof.', name: 'Niteshkumar Yadav', fullName: 'Prof. Niteshkumar Yadav', block: 'S-415', floor: '4th', cabinPosition: 'H (Left First)', cabinType: 'lettered', rawRemark: 'Pro VC Reserved', remarkType: 'note', isHOD: false },
  { id: 51, title: 'Prof.', name: 'Uday Mande', fullName: 'Prof. Uday Mande', block: 'S-502', floor: '5th', cabinPosition: '1', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 52, title: 'Prof.', name: 'Rahul Bembade', fullName: 'Prof. Rahul Bembade', block: 'S-502', floor: '5th', cabinPosition: '2', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 53, title: 'Prof.', name: 'Viresh Vanarote', fullName: 'Prof. Viresh Vanarote', block: 'S-502', floor: '5th', cabinPosition: '3', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 54, title: 'Prof.', name: 'Pooja Kadam', fullName: 'Prof. Pooja Kadam', block: 'S-502', floor: '5th', cabinPosition: '4', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 55, title: 'Prof.', name: 'Aman Kamble', fullName: 'Prof. Aman Kamble', block: 'S-502', floor: '5th', cabinPosition: '5', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 56, title: 'Prof.', name: 'Tejaswini Bhosale', fullName: 'Prof. Tejaswini Bhosale', block: 'S-502', floor: '5th', cabinPosition: '6', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 57, title: 'Prof.', name: 'Pankaj Chandre', fullName: 'Prof. Pankaj Chandre', block: 'S-504', floor: '5th', cabinPosition: '1', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 58, title: 'Prof.', name: 'Rahul More', fullName: 'Prof. Rahul More', block: 'S-504', floor: '5th', cabinPosition: '2', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 59, title: 'Prof.', name: 'Hingoliwala Hyder Ali', fullName: 'Prof. Hingoliwala Hyder Ali', block: 'S-504', floor: '5th', cabinPosition: '3', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 60, title: 'Prof.', name: 'Ravirai Choudhari', fullName: 'Prof. Ravirai Choudhari', block: 'S-504', floor: '5th', cabinPosition: '4', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 61, title: 'Prof.', name: 'Swapnil Patil', fullName: 'Prof. Swapnil Patil', block: 'S-504', floor: '5th', cabinPosition: '5', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 62, title: 'Prof.', name: 'Tanuja Zende', fullName: 'Prof. Tanuja Zende', block: 'S-504', floor: '5th', cabinPosition: '6', cabinType: 'numbered', rawRemark: 'Prof. Madhukar Nimbalkar Shifted to Admin', remarkType: 'note', isHOD: false },
  { id: 63, title: 'Prof.', name: 'Moushmee Kuri', fullName: 'Prof. Moushmee Kuri', block: 'S-504', floor: '5th', cabinPosition: '7', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 64, title: 'Prof.', name: 'Viddulata Patil', fullName: 'Prof. Viddulata Patil', block: 'S-504', floor: '5th', cabinPosition: '8', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 65, title: 'Prof.', name: 'Vrushali Kondhalkar', fullName: 'Prof. Vrushali Kondhalkar', block: 'S-511', floor: '5th', cabinPosition: 'A (Right First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 66, title: 'Prof.', name: 'Pratik Kamble', fullName: 'Prof. Pratik Kamble', block: 'S-511', floor: '5th', cabinPosition: 'B (Right Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 67, title: 'Dr.', name: 'Vinodpuri Rampuri Gosavi', fullName: 'Dr. Vinodpuri Rampuri Gosavi', block: 'S-511', floor: '5th', cabinPosition: 'C (Right Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 68, title: 'Prof.', name: 'Rinku Badgujar', fullName: 'Prof. Rinku Badgujar', block: 'S-511', floor: '5th', cabinPosition: 'D (Right Fourth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 69, title: 'Dr.', name: 'Harshad Lokhande', fullName: 'Dr. Harshad Lokhande', block: 'S-511', floor: '5th', cabinPosition: 'E (Left Fourth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 70, title: 'Prof.', name: 'Chaitanya Garware', fullName: 'Prof. Chaitanya Garware', block: 'S-511', floor: '5th', cabinPosition: 'F (Left Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 71, title: 'Prof.', name: 'Nilesh Kullal', fullName: 'Prof. Nilesh Kullal', block: 'S-511', floor: '5th', cabinPosition: 'G (Left Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 72, title: 'Prof.', name: 'Smita Gumaste', fullName: 'Prof. Smita Gumaste', block: 'S-511', floor: '5th', cabinPosition: 'H (Left First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 73, title: 'Prof.', name: 'Manisha Galphade', fullName: 'Prof. Manisha Galphade', block: 'S-513', floor: '5th', cabinPosition: 'A (Right First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 74, title: 'Dr.', name: 'Mayura Shelke', fullName: 'Dr. Mayura Shelke', block: 'S-513', floor: '5th', cabinPosition: 'B (Right Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 75, title: 'Prof.', name: 'Amol Jagannath Dande', fullName: 'Prof. Amol Jagannath Dande', block: 'S-513', floor: '5th', cabinPosition: 'C (Right Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 76, title: 'Prof.', name: 'Amit Uttarkar', fullName: 'Prof. Amit Uttarkar', block: 'S-513', floor: '5th', cabinPosition: 'D (Right Fourth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 77, title: 'Dr.', name: 'Saleha Saudagar', fullName: 'Dr. Saleha Saudagar', block: 'S-513', floor: '5th', cabinPosition: 'E (Left Fourth)', cabinType: 'lettered', rawRemark: 'Shifted from S-211', remarkType: 'shifted', isHOD: false },
  { id: 79, title: 'Dr.', name: 'Megha Mahesh Wankhade', fullName: 'Dr. Megha Mahesh Wankhade', block: 'S-513', floor: '5th', cabinPosition: 'G (Left Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 80, title: 'Prof.', name: 'Vishal Maloji Patil', fullName: 'Prof. Vishal Maloji Patil', block: 'S-513', floor: '5th', cabinPosition: 'H (Left First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 81, title: 'Dr.', name: 'Anant Kaulge', fullName: 'Dr. Anant Kaulge', block: 'S-602', floor: '6th', cabinPosition: '1', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 82, title: 'Prof.', name: 'Hemant Shinde', fullName: 'Prof. Hemant Shinde', block: 'S-602', floor: '6th', cabinPosition: '2', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 83, title: 'Dr.', name: 'Sagar Tambe', fullName: 'Dr. Sagar Tambe', block: 'S-602', floor: '6th', cabinPosition: '3', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 84, title: 'Prof.', name: 'Shrikant Dhage', fullName: 'Prof. Shrikant Dhage', block: 'S-602', floor: '6th', cabinPosition: '4', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 85, title: 'Prof.', name: 'Pournima Sutar', fullName: 'Prof. Pournima Sutar', block: 'S-602', floor: '6th', cabinPosition: '5', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 86, title: 'Prof.', name: 'Rohidas Sangore', fullName: 'Prof. Rohidas Sangore', block: 'S-602', floor: '6th', cabinPosition: '6', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 87, title: 'Dr.', name: 'Mansi Bhosale', fullName: 'Dr. Mansi Bhosale', block: 'S-616', floor: '6th', cabinPosition: 'A (Right First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 88, title: 'Prof.', name: 'Manoj Shinde', fullName: 'Prof. Manoj Shinde', block: 'S-616', floor: '6th', cabinPosition: 'B (Right Second)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 89, title: 'Dr.', name: 'Sachin Thanekar', fullName: 'Dr. Sachin Thanekar', block: 'S-616', floor: '6th', cabinPosition: 'C (Right Third)', cabinType: 'lettered', rawRemark: 'Cabin area converted to Pantry', remarkType: 'note', isHOD: false },
  { id: 90, title: 'Dr.', name: 'Sharan Christa', fullName: 'Dr. Sharan Christa', block: 'S-616', floor: '6th', cabinPosition: 'D (Right Fourth)', cabinType: 'lettered', rawRemark: 'Dr. Nandkumar Kulkarni Shifted to HOD Office', remarkType: 'note', isHOD: false },
  { id: 91, title: 'Prof.', name: 'Bhushan Bhokse', fullName: 'Prof. Bhushan Bhokse', block: 'S-616', floor: '6th', cabinPosition: 'E (Left Fourth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 92, title: 'Dr.', name: 'Amol Bhosale', fullName: 'Dr. Amol Bhosale', block: 'S-616', floor: '6th', cabinPosition: 'F (Left Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 93, title: 'Dr.', name: 'Abhishek M. Dhore', fullName: 'Dr. Abhishek M. Dhore', block: 'S-616', floor: '6th', cabinPosition: 'G (Left Second)', cabinType: 'lettered', rawRemark: 'Previous occupant shifted to NP Sir Cabin', remarkType: 'note', isHOD: false },
  { id: 94, title: 'Dr.', name: 'P. D. Patil', fullName: 'Dr. P. D. Patil', block: 'S-616', floor: '6th', cabinPosition: 'H (Left First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 95, title: 'Dr.', name: 'Hari Kumar Palani', fullName: 'Dr. Hari Kumar Palani', block: 'S-616', floor: '6th', cabinPosition: '1', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 96, title: 'Prof.', name: 'Deepali Lokare', fullName: 'Prof. Deepali Lokare', block: 'S-616', floor: '6th', cabinPosition: '2', cabinType: 'numbered', rawRemark: 'On Leave — Temp seat: Supriya Jadhav', remarkType: 'on_leave', isHOD: false },
  { id: 97, title: 'Dr.', name: 'Amreen Khan', fullName: 'Dr. Amreen Khan', block: 'N-409', floor: '4th', cabinPosition: '3', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 98, title: 'Prof.', name: 'Hanumant Aba Pawar', fullName: 'Prof. Hanumant Aba Pawar', block: 'N-409', floor: '4th', cabinPosition: '4', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 99, title: 'Dr.', name: 'Nilima Ramteke', fullName: 'Dr. Nilima Ramteke', block: 'N-409', floor: '4th', cabinPosition: '5', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 100, title: 'Prof.', name: 'Shweta Yadav', fullName: 'Prof. Shweta Yadav', block: 'N-409', floor: '4th', cabinPosition: '6', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 101, title: 'Prof.', name: 'Anuja Gaikwad', fullName: 'Prof. Anuja Gaikwad', block: 'N-409', floor: '4th', cabinPosition: '7', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 102, title: 'Prof.', name: 'Tushar Mote', fullName: 'Prof. Tushar Mote', block: 'N-410', floor: '4th', cabinPosition: '1', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 103, title: 'Prof.', name: 'Vijaya Samadhan Patil', fullName: 'Prof. Vijaya Samadhan Patil', block: 'N-410', floor: '4th', cabinPosition: '2', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 104, title: 'Dr.', name: 'Nitish Das', fullName: 'Dr. Nitish Das', block: 'N-410', floor: '4th', cabinPosition: '3', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 105, title: 'Dr.', name: 'Mukund Wagh', fullName: 'Dr. Mukund Wagh', block: 'N-410', floor: '4th', cabinPosition: '4', cabinType: 'numbered', rawRemark: 'Dr. Suvarna Pawar moved to HOD Cabin', remarkType: 'note', isHOD: false },
  { id: 106, title: 'Prof.', name: 'Jyoti Manoorkar', fullName: 'Prof. Jyoti Manoorkar', block: 'N-410', floor: '4th', cabinPosition: '5', cabinType: 'numbered', rawRemark: 'Tanuja Mam Shifted to S-504', remarkType: 'note', isHOD: false },
  { id: 107, title: 'Prof.', name: 'Shraddha Kashid', fullName: 'Prof. Shraddha Kashid', block: 'N-410', floor: '4th', cabinPosition: '6', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 108, title: 'Dr.', name: 'Zakir Shaikh', fullName: 'Dr. Zakir Shaikh', block: 'N-410', floor: '4th', cabinPosition: '7', cabinType: 'numbered', rawRemark: 'Dr. Neha Gupta Left', remarkType: 'note', isHOD: false },
  { id: 109, title: 'Dr.', name: 'Rashmi S Nair', fullName: 'Dr. Rashmi S Nair', block: 'N-502', floor: '5th', cabinPosition: '1', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 110, title: 'Prof.', name: 'Rashmi Tundalwar', fullName: 'Prof. Rashmi Tundalwar', block: 'N-502', floor: '5th', cabinPosition: '2', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 111, title: 'Dr.', name: 'Anuja Jadhav', fullName: 'Dr. Anuja Jadhav', block: 'N-502', floor: '5th', cabinPosition: '3', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 112, title: 'Prof.', name: 'Anuja Chincholikar', fullName: 'Prof. Anuja Chincholikar', block: 'N-502', floor: '5th', cabinPosition: '4', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 113, title: 'Prof.', name: 'Suruchi Deshmukh', fullName: 'Prof. Suruchi Deshmukh', block: 'N-504', floor: '5th', cabinPosition: '1', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 114, title: 'Prof.', name: 'Tushar Mane & Revati Raspale', fullName: 'Prof. Tushar Mane & Revati Raspale', block: 'N-504', floor: '5th', cabinPosition: '2', cabinType: 'numbered', rawRemark: 'Two faculty sharing (Dr. Umang Garg previously Left)', remarkType: 'sharing', isHOD: false },
  { id: 115, title: 'Dr.', name: 'Jagannath Nalavade', fullName: 'Dr. Jagannath Nalavade', block: 'N-504', floor: '5th', cabinPosition: '3', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 116, title: 'Prof.', name: 'Dattatray Kale', fullName: 'Prof. Dattatray Kale', block: 'N-504', floor: '5th', cabinPosition: '4', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 117, title: 'Dr.', name: 'Sumit Hirave', fullName: 'Dr. Sumit Hirave', block: 'N-504', floor: '5th', cabinPosition: '5', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 118, title: 'Dr.', name: 'Rajendra Pawar', fullName: 'Dr. Rajendra Pawar', block: 'N-504', floor: '5th', cabinPosition: '6', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 119, title: 'Prof.', name: 'Sonali Arvind Deshpande', fullName: 'Prof. Sonali Arvind Deshpande', block: 'N-504', floor: '5th', cabinPosition: '7', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 120, title: 'Dr.', name: 'Suvarna Joshi', fullName: 'Dr. Suvarna Joshi', block: 'N-504', floor: '5th', cabinPosition: '8', cabinType: 'numbered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 121, title: 'Ms.', name: 'Rutuja Sanjay Patil', fullName: 'Ms. Rutuja Sanjay Patil', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 1', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 122, title: 'Ms.', name: 'Sharayu Anap', fullName: 'Ms. Sharayu Anap', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 2', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 123, title: 'Prof.', name: 'Shruti Tilwant', fullName: 'Prof. Shruti Tilwant', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 3', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 124, title: 'Prof.', name: 'Shahin Makubhai', fullName: 'Prof. Shahin Makubhai', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 4', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 125, title: 'Prof.', name: 'Aparna Torade', fullName: 'Prof. Aparna Torade', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 5', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 126, title: 'Dr.', name: 'Monali Tingane', fullName: 'Dr. Monali Tingane', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 6', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 127, title: 'Mr.', name: 'Abhijeet Dinkar Cholke', fullName: 'Mr. Abhijeet Dinkar Cholke', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 7', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 128, title: 'Prof.', name: 'Vishal Bogam', fullName: 'Prof. Vishal Bogam', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 8', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 129, title: 'Prof.', name: 'Sushant Shirbhate', fullName: 'Prof. Sushant Shirbhate', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 9', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 130, title: 'Prof.', name: 'Shrikant A. Shinde', fullName: 'Prof. Shrikant A. Shinde', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 10', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 132, title: 'Mrs.', name: 'Archana Pakhare', fullName: 'Mrs. Archana Pakhare', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 12', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 133, title: 'Mrs.', name: 'Sonal Chanderi', fullName: 'Mrs. Sonal Chanderi', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 13', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 135, title: 'Prof.', name: 'Pooja Pawale', fullName: 'Prof. Pooja Pawale', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 15', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 136, title: 'Prof.', name: 'Renuka Arbat', fullName: 'Prof. Renuka Arbat', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 16', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 137, title: 'Prof.', name: 'Swati Kadam', fullName: 'Prof. Swati Kadam', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 17', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 138, title: 'Prof.', name: 'Abhishek Das', fullName: 'Prof. Abhishek Das', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 18', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 139, title: 'Prof.', name: 'Arun Ghandat', fullName: 'Prof. Arun Ghandat', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 19', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 141, title: 'Prof.', name: 'Sneha Deshmukh', fullName: 'Prof. Sneha Deshmukh', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 21', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 142, title: 'Prof.', name: 'Pratiksha Dhande', fullName: 'Prof. Pratiksha Dhande', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 22', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 145, title: 'Prof.', name: 'Sneha Singha', fullName: 'Prof. Sneha Singha', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 25', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 146, title: 'Prof.', name: 'Ruchita Sharma', fullName: 'Prof. Ruchita Sharma', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 26', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 148, title: 'Prof.', name: 'Nisha Chobe', fullName: 'Prof. Nisha Chobe', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 28', cabinType: 'cubicle', rawRemark: 'On Maternity Leave', remarkType: 'maternity_leave', isHOD: false },
  { id: 149, title: 'Miss.', name: 'Siddhi Mahulkar', fullName: 'Miss. Siddhi Mahulkar', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 29', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 150, title: 'Prof.', name: 'Sumedha Ayachit', fullName: 'Prof. Sumedha Ayachit', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 30', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 151, title: 'Mr.', name: 'Sumit Chuttar', fullName: 'Mr. Sumit Chuttar', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 31', cabinType: 'cubicle', rawRemark: 'Entrepreneurship', remarkType: 'entrepreneurship', isHOD: false },
  { id: 152, title: 'Prof.', name: 'Bajirao Salunkhe', fullName: 'Prof. Bajirao Salunkhe', block: 'J-901', floor: '9th', cabinPosition: 'Cubicle 32', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 153, title: 'Prof.', name: 'Swapnil Chaudhari', fullName: 'Prof. Swapnil Chaudhari', block: 'S-901', floor: '9th', cabinPosition: 'A (Right First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 155, title: 'Ms.', name: 'Prajwalita Ramdasrao Dongre', fullName: 'Ms. Prajwalita Ramdasrao Dongre', block: 'S-901', floor: '9th', cabinPosition: 'C (Right Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 156, title: 'Prof.', name: 'Vikas More', fullName: 'Prof. Vikas More', block: 'S-901', floor: '9th', cabinPosition: 'D (Right Fourth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 157, title: 'Prof.', name: 'Sachin Tiwari', fullName: 'Prof. Sachin Tiwari', block: 'S-901', floor: '9th', cabinPosition: 'E (Right Fifth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 158, title: 'Prof.', name: 'Rupesh Hushangabade', fullName: 'Prof. Rupesh Hushangabade', block: 'S-901', floor: '9th', cabinPosition: 'F (Right Sixth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 159, title: 'Prof.', name: 'Rajesh Halke', fullName: 'Prof. Rajesh Halke', block: 'S-901', floor: '9th', cabinPosition: 'G (Right Seventh)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 160, title: 'Prof.', name: 'Swati Power', fullName: 'Prof. Swati Power', block: 'S-901', floor: '9th', cabinPosition: 'H (Left Seventh)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 161, title: 'Dr.', name: 'Umar M Mulani', fullName: 'Dr. Umar M Mulani', block: 'S-901', floor: '9th', cabinPosition: 'I (Left Sixth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 162, title: 'Prof.', name: 'Shilpa Dhopte', fullName: 'Prof. Shilpa Dhopte', block: 'S-901', floor: '9th', cabinPosition: 'J (Left Fifth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 163, title: 'Prof.', name: 'Deepak Naik', fullName: 'Prof. Deepak Naik', block: 'S-901', floor: '9th', cabinPosition: 'K (Left Fourth)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 164, title: 'Prof.', name: 'Nitin Alzende', fullName: 'Prof. Nitin Alzende', block: 'S-901', floor: '9th', cabinPosition: 'L (Left Third)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 165, title: 'Prof.', name: 'Sheetal Aher', fullName: 'Prof. Sheetal Aher', block: 'S-901', floor: '9th', cabinPosition: 'M (Left Second)', cabinType: 'lettered', rawRemark: 'Near Pillar', remarkType: 'note', isHOD: false },
  { id: 166, title: 'Dr.', name: 'Vishnu Suryvanshi', fullName: 'Dr. Vishnu Suryvanshi', block: 'S-901', floor: '9th', cabinPosition: 'N (Left First)', cabinType: 'lettered', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 167, title: 'Prof.', name: 'Shital Dumbare', fullName: 'Prof. Shital Dumbare', block: 'S-901', floor: '9th', cabinPosition: 'Cubicle A', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 168, title: 'Prof.', name: 'Ashwini Shahapurkar', fullName: 'Prof. Ashwini Shahapurkar', block: 'S-901', floor: '9th', cabinPosition: 'Cubicle B', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 169, title: 'Prof.', name: 'Sharddha Katkar', fullName: 'Prof. Sharddha Katkar', block: 'S-901', floor: '9th', cabinPosition: 'Cubicle C', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 170, title: 'Prof.', name: 'Simran Ahuja', fullName: 'Prof. Simran Ahuja', block: 'S-901', floor: '9th', cabinPosition: 'Cubicle D', cabinType: 'cubicle', rawRemark: 'Seating at IT Department', remarkType: 'note', isHOD: false },
  { id: 173, title: 'Dr.', name: 'Arati Kale', fullName: 'Dr. Arati Kale', block: 'S-901', floor: '9th', cabinPosition: 'Cubicle G', cabinType: 'cubicle', rawRemark: '', remarkType: 'none', isHOD: false },
  { id: 174, title: 'Miss.', name: 'Manujala Nair', fullName: 'Miss. Manujala Nair', block: 'S-901', floor: '9th', cabinPosition: 'Cubicle H', cabinType: 'cubicle', rawRemark: 'Entrepreneurship', remarkType: 'entrepreneurship', isHOD: false },
  { id: 191, title: 'Prof.', name: 'Namrata Naikwade', fullName: 'Prof. Namrata Naikwade', block: 'LAB-S608', floor: '6th', cabinPosition: 'Lab Cabin S608', cabinType: 'lab', rawRemark: '', remarkType: 'none', isHOD: false },
];

async function main() {
  console.log('Seeding faculty records...');

  for (const record of FACULTY_DATA) {
    await prisma.facultyRecord.upsert({
      where: { id: record.id },
      update: record,
      create: record,
    });
  }

  console.log(`Seeded ${FACULTY_DATA.length} faculty records.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
